
INIT: Using found mnist data
2022-04-06 12:47:44.398852: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-06 12:47:44.398966: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (e175316c4453): /proc/driver/nvidia/version does not exist
2022-04-06 12:47:44.399399: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
MAIN: Started Training
Length Calculated:  1750
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
nas- 55994
used 0 epoch
label        0
score    55994
0            0
dtype: int64
nas- 0
pacing dataused  5599
nas- 50395
       label  score          0
i
64656      2    0.0   0.000006
25534      2    1.0   0.000007
52691      0    2.0    0.00001
14744      2    3.0   0.000013
58330      7    4.0   0.000014
...      ...    ...        ...
10905      4    NaN  10.727668
31745      7    NaN  11.155935
20443      4    NaN  11.439095
43515      3    NaN  13.699946
41103      4    NaN  13.929952
[55994 rows x 3 columns]
nas- 55994
nas- 50395
                                                     img  label   score
i
64099  [  0   0   0   0   0   0   0   0   0   0   0  ...      0     NaN
449    [  0   0   0   0   0   0   0   0   0   0   0  ...      0     NaN
26581  [  0   0   0   0   0   0   0   0   0   0   0  ...      4     NaN
23290  [  0   0   0   0   0   0   0   0   0   0   0  ...      9     NaN
6643   [  0   0   0   0   0   0   0   0   0   0   0  ...      4     NaN
...                                                  ...    ...     ...
39708  [  0   0   0   0   0   0   0   0   0   0   0  ...      0   965.0
39682  [  0   0   0   0   0   0   0   0   0   0   0  ...      6  1081.0
55088  [  0   0   0   0   0   0   0   0   0   0   0  ...      3     NaN
34253  [  0   0   0   0   0   0   0   0   0   0   0  ...      5     NaN
60173  [  0   0   0   0   0   0   0   0   0   0   0  ...      6  3939.0
[55994 rows x 3 columns]
df-len- 55994
nas- 50395
dataused-on-epoch-end- 5599
[1270, 141, 1098, 662, 555, 89, 714, 949, 111, 10]
Length Calculated:  438
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2022-04-06 12:50:46.141356: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Epoch  1 , Loss:  0.48578298 , Accuracy:  0.8661821 , Test Loss:  0.26590312 , Test Accuracy:  0.92039126
Checkpoint saved
Length Calculated:  175
Batch =0
Batch =100
nas- 50395
use reduced grads
label        0
score    55994
0            0
1        50394
dtype: int64
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
Traceback (most recent call last):
  File "RunTest.py", line 216, in <module>
    main(args)
  File "RunTest.py", line 146, in main
    df_train_losses = sf.scoring_func(df_train_losses,info) # =(i|score,0,1,2...)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 149, in scoring_func
    print('use full grads')
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 115, in calc_grad
    model = linear_model.LinearRegression().fit(x,y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_base.py", line 669, in fit
    X, y, X_offset, y_offset, X_scale = self._preprocess_data(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_base.py", line 247, in _preprocess_data
    X = check_array(X, copy=copy, accept_sparse=["csr", "csc"], dtype=FLOAT_DTYPES)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 103, in _assert_all_finite
    if is_float and (np.isfinite(_safe_accumulator_op(np.sum, X))):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/extmath.py", line 895, in _safe_accumulator_op
    result = op(x, *args, **kwargs)
  File "<__array_function__ internals>", line 180, in sum
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 2296, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
KeyboardInterrupt