
INIT: Using found mnist data
2022-04-05 14:51:49.161431: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-05 14:51:49.161611: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (69dc0e526fe3): /proc/driver/nvidia/version does not exist
2022-04-05 14:51:49.162303: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
MAIN: Started Training
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
   label  score         0
i
0      2    NaN  0.023255
1      0    NaN  0.002609
2      4    NaN  0.030389
3      8    NaN  0.200189
6      0    NaN  0.000685
used 0 epoch
   label     score         0
i
0      2  0.023255  0.023255
1      0  0.002609  0.002609
2      4  0.030389  0.030389
3      8  0.200189  0.200189
6      0  0.000685  0.000685
       label  score         0
i
8473       2    0.0  0.000009
52691      0    1.0   0.00001
62977      0    2.0  0.000017
25367      2    3.0  0.000018
62848      2    4.0  0.000018
                                                     img  label  score
i
8473   [  0   0   0   0   0   0   0   0   0   0   0  ...      2    0.0
52691  [  0   0   0   0   0   0   0   0   0   0   0  ...      0    1.0
62977  [  0   0   0   0   0   0   0   0   0   0   0  ...      0    2.0
25367  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    3.0
62848  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    4.0
...                                                  ...    ...    ...
2978   [  0   0   0   0   0   0   0   0   0   0   0  ...      6    NaN
54929  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    NaN
19013  [  0   0   0   0   0   0   0   0   0   0   0  ...      5    NaN
23781  [  0   0   0   0   0   0   0   0   0   0   0  ...      0    NaN
8233   [  0   0   0   0   0   0   0   0   0   0   0  ...      3    NaN
[55994 rows x 3 columns]
55994
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
Epoch  1 , Loss:  0.5041965 , Accuracy:  0.86331475 , Test Loss:  0.2647914 , Test Accuracy:  0.92126715
2022-04-05 14:54:23.330482: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Checkpoint saved
Batch =0
Batch =100
Batch =200
Traceback (most recent call last):
  File "RunTest.py", line 193, in <module>
    main(args)
  File "RunTest.py", line 134, in main
    col = sf.update_col(batch_loss,col,X[0],info) # = (i,current_epoch)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 195, in update_col
    new_row = pd.DataFrame(data={'i':indexes[i],str(info.current_epoch):batch_loss[i].numpy()},index=[0])
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py", line 1096, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/array_ops.py", line 1042, in _slice_helper
    return strided_slice(
KeyboardInterrupt