2022-04-05 10:43:12.628638: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-05 10:43:12.628704: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (69dc0e526fe3): /proc/driver/nvidia/version does not exist
2022-04-05 10:43:12.628920: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Using found mnist data
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
MAIN: Started Training
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Traceback (most recent call last):
  File "RunTest.py", line 181, in <module>
    main(args)
  File "RunTest.py", line 133, in main
    col = sf.update_col(batch_loss,col,X[0],info) # = (i,current_epoch)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 193, in update_col
    col = pd.concat([col,new_row],axis=0)
KeyboardInterrupt